language: ruby
rvm:
- 2.3.3

before_script:
- openssl aes-256-cbc -K $encrypted_8f2e1fe0e7f3_key -iv $encrypted_8f2e1fe0e7f3_iv
  -in travis.enc -out ~/.ssh/id_rsa -d
  #本句是服务器上的 Travis 自动生成的，但默认生成的命令可能会在/前面带转义符\，我们不需要这些转义符，手动删掉所有的转义符，否则可能在后面引发莫名的错误。
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 39.105.90.225\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config #106.15.190.249 是服务器IP，修改成你自己的就行

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
install: 
- gem install jekyll
- gem install jekyll-paginate

script: jekyll build #&& htmlproofer ./_site #指定目录容易报错

after_success:
  - git clone https://github.com/gy0624ww/guanyue_blog.git
  - cd guanyue_blog && rm -rf * && cp -r ../_site/* .
  - git config user.name "gy0624ww"
  - git config user.email "gy0624ww@gmail.com"
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force https://$DEPLOY_TOKEN@github.com/gy0624ww/blog-article.git master
  # Trigger all tags/branchs for this automated build.
  - curl -X POST https://registry.hub.docker.com/u/gy0624ww/blog-dockerfiles/trigger/66b7a9b2-b17c-471f-ab14-ab015b05d362/  #本句的链接是hub.docker.com 自动生成，进入docker项目后，Building Settings - Build Triggers - Activate Triggers ，复制 Trigger URL
  - sleep 5m #超过10分钟，tavis 将失去响应。此处是在等待 docker 镜像更新
  - ssh root@39.105.90.225 -p 22 -o StrictHostKeyChecking=no "docker pull gy0624ww/blog-dockerfiles && docker stop guanyue_blog && docker rm guanyue_blog && docker run --name=guanyue_blog -d -p 39100:80 --privileged=true gy0624ww/blog-dockerfiles:latest"  #ssh 连接后，重启 docker 容器, jekyll_blog 为之前设定的容器名。

# branch whitelist, only for Github Pages
branchs:
  only:
  - master  #指定只有检测到master分支有变动时才执行任务

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  ssh_known_hosts:
  - 39.105.90.225 #受信主机，你的Linux服务器ip

sudo: false # route your build to the container-based infrastructure for a faster build
